# Generated by Django 4.0.3 on 2022-04-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='user.generaluser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.generaluser')),
            ],
        ),
    ]
