# Generated by Django 4.0.3 on 2022-04-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='noteId',
            field=models.IntegerField(default=0),
        ),
    ]
