# Generated by Django 4.0.3 on 2022-04-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_alter_like_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='noteId',
        ),
    ]
