# Generated by Django 4.0.3 on 2022-05-06 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
