# Generated by Django 4.0.3 on 2022-04-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='noteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_note_user', to='user.generaluser'),
        ),
    ]
