# Generated by Django 4.0.3 on 2022-04-29 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_noteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
