# Generated by Django 4.0.3 on 2022-05-06 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimage',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
