# Generated by Django 4.0.3 on 2022-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_generaluser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roomType', models.IntegerField(default=0)),
                ('lock', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=30)),
                ('user', models.ManyToManyField(to='user.generaluser')),
            ],
        ),
    ]
