# Generated by Django 4.0.3 on 2022-05-03 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
