# Generated by Django 4.0.3 on 2022-05-06 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='editDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
