# Generated by Django 4.0.3 on 2022-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_editdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='editDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
