# Generated by Django 4.0.3 on 2022-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(max_length=8),
        ),
    ]
