# Generated by Django 4.0.3 on 2022-04-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_alter_bug_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
