# Generated by Django 4.0.3 on 2022-04-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
