# Generated by Django 4.0.3 on 2022-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
