# Generated by Django 4.0.3 on 2022-04-18 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createdTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
