# Generated by Django 4.0.3 on 2022-04-18 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_remove_comment_createdtime_alter_comment_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
