# Generated by Django 4.0.3 on 2022-04-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_createddate'),
        ('answer', '0002_alter_answer_question'),
        ('user', '0001_initial'),
        ('note', '0002_note_createddate'),
        ('comment', '0006_alter_comment_createddate'),
        ('report', '0002_report_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answer.answer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.note'),
        ),
        migrations.AlterField(
            model_name='report',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_profile', to='user.generaluser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
