# Generated by Django 4.0.3 on 2022-04-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
